version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: lab_admin
      POSTGRES_PASSWORD: lab_admin
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_db_volume: