apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-lab-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClass }}
  hostPath:
    path: "{{ .Values.storage.hostPath }}"