# templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jenkins.persistence.size }}

# # templates/networkpolicy.yaml (optional)
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: {{ .Release.Name }}-jenkins-networkpolicy
# spec:
#   podSelector:
#     matchLabels:
#       app: jenkins
#   policyTypes:
#     - Ingress
#     - Egress
