apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.job.name }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "jenkins_lab.name" . }}-cleanup
    chart: {{ include "jenkins_lab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.job.name }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "jenkins_lab.name" . }}-cleanup
    chart: {{ include "jenkins_lab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.job.name }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "jenkins_lab.name" . }}-cleanup
    chart: {{ include "jenkins_lab.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: {{ .Values.job.name }}-cleanup
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.job.name }}-cleanup
  apiGroup: rbac.authorization.k8s.io